name: test action
description: A reusable set of test steps
inputs:
  pg_version:
    description: 'PostgreSQL version'
    required: true
  container_os:
    description: 'Container OS'
    required: true
  test_make_target:
    description: 'Test make target'
    required: true
  from_pg_version:
    description: 'PostgreSQL version to upgrade from'
    required: false
    default: ''
  installcheck:
    description: 'Runs an installcheck test'
    required: false
    default: 'false'
  installcheck_postgres:
    description: 'Runs an installcheck-postgres test'
    required: false
    default: 'false'
  isolation:
    description: 'Runs an isolation test'
    required: false
    default: 'false'
  upgrade:
    description: 'Runs an upgrade test'
    required: false
    default: 'false'
  worker_count:
    description: 'Number of workers for split tests'
    required: false
    default: ''
  worker_id:
    description: 'Worker ID for split tests'
    required: false
    default: ''

runs:
  using: "composite"
  steps:
    - name: Export CI_WORKER_COUNT and CI_WORKER_ID
      if: ${{ inputs.worker_count != '' }}
      shell: bash
      run: |
        echo "CI_WORKER_COUNT=${{ inputs.worker_count }}" >> $GITHUB_ENV
        echo "CI_WORKER_ID=${{ inputs.worker_id }}" >> $GITHUB_ENV

    - name: Export PGDIR, PATH and PG_REGRESS_DIR
      shell: bash
      run: |
        echo "PGDIR=/home/postgres/pgsql-${{ inputs.pg_version }}" >> $GITHUB_ENV
        echo "PATH=/home/postgres/pgsql-${{ inputs.pg_version }}/bin:$PATH" >> $GITHUB_ENV
        echo "PG_REGRESS_DIR=/home/postgres/pgsql-${{ inputs.pg_version }}/regress" >> $GITHUB_ENV

    - name: Download postgres-${{ inputs.pg_version }} artifacts
      uses: actions/download-artifact@v4
      with:
        name: postgres-${{ inputs.pg_version }}-${{ inputs.container_os }}-artifacts
        path: /home/postgres/pgsql-${{ inputs.pg_version }}/

    - name: Download postgres (from_pg_version) artifacts
      if: ${{ inputs.upgrade == 'true' }}
      uses: actions/download-artifact@v4
      with:
        name: postgres-${{ inputs.from_pg_version }}-${{ inputs.container_os }}-artifacts
        path: /home/postgres/pgsql-${{ inputs.from_pg_version }}/

    # avro tests needs a clean environment
    - name: Download avro artifacts for ${{ inputs.container_os }}
      if: ${{ inputs.test_make_target != 'check-avro' }}
      uses: actions/download-artifact@v4
      with:
        name: avro-${{ inputs.container_os }}-artifacts
        path: |
          ./avro/lang/c/build/avrolib

    # download-artifact does not preserve folder permissions
    - name: Adjust permissions
      shell: bash
      run: |
        chmod 755 /home/postgres/pgsql-${{ inputs.pg_version }}/bin/pgduck_server
        chmod 755 /home/postgres/pgsql-${{ inputs.pg_version }}/lib/*.so

        if [ ${{ inputs.upgrade }} == 'true' ]; then
          chmod 755 /home/postgres/pgsql-${{ inputs.from_pg_version }}/bin/pgduck_server
          chmod 755 /home/postgres/pgsql-${{ inputs.from_pg_version }}/lib/*.so
        fi

    - uses: actions/cache@v4
      name: Cache pipenv
      with:
        path: ~/.local/share/virtualenvs
        key: pipenv-${{ inputs.container_os }}-${{ hashFiles('Pipfile.lock') }}

    - name: Run test
      shell: bash
      run: |
        if [ ${{ inputs.installcheck }} == 'true' ]; then
          pgduck_server --init_file_path pgduck_server/tests/test_secrets.sql --extensions_dir /tmp/extensions --cache_dir /tmp/cache > /tmp/pgduck_installcheck_logs 2>&1 &
          
          initdb -D /tmp/pg_installcheck_tests -U postgres --set "shared_preload_libraries=pg_extension_base,pg_cron,pg_lake_table,pg_lake_copy,pg_lake,pgaudit,pg_stat_statements" --locale=C.UTF-8 --data-checksums
          
          echo "listen_addresses = 'localhost'" >> /tmp/pg_installcheck_tests/postgresql.conf
          echo "max_worker_processes = 100" >> /tmp/pg_installcheck_tests/postgresql.conf
          echo "pg_lake_engine.orphaned_file_retention_period=0" >> /tmp/pg_installcheck_tests/postgresql.conf
          echo "pg_lake_iceberg.autovacuum_naptime=5" >> /tmp/pg_installcheck_tests/postgresql.conf
          echo "unix_socket_directories = '/tmp/pg_installcheck_tests'" >> /tmp/pg_installcheck_tests/postgresql.conf
          echo "max_prepared_transactions = 100" >> /tmp/pg_installcheck_tests/postgresql.conf
          echo "pgaudit.log='all'" >> /tmp/pg_installcheck_tests/postgresql.conf

          if [ ${{ inputs.installcheck_postgres }} == 'true' ]; then
            echo "compute_query_id='regress'" >> /tmp/pg_installcheck_tests/postgresql.conf
            echo "pg_lake_table.hide_objects_created_by_lake=true" >> /tmp/pg_installcheck_tests/postgresql.conf
          fi

          echo "host postgres postgres 127.0.0.1/32 md5" >> /tmp/pg_installcheck_tests/pg_hba.conf

          pg_ctl -D /tmp/pg_installcheck_tests -l /tmp/pg_installcheck_tests/logfile -w start
          psql -U postgres -d postgres -h localhost -p 5432 -c "ALTER USER postgres WITH PASSWORD 'postgres';"
          psql -U postgres -d postgres -h localhost -p 5432 -c "CREATE DATABASE regression;"
          psql -U postgres -d regression -h localhost -p 5432 -c "CREATE EXTENSION pg_lake CASCADE;"
          psql -U postgres -d regression -h localhost -p 5432 -c "CREATE EXTENSION pg_lake_spatial CASCADE;"

          make ${{ inputs.test_make_target }}
        elif [ ${{ inputs.upgrade }} == 'true' ]; then
          TEST_PG_UPGRADE_FROM_BINDIR=/home/postgres/pgsql-${{ inputs.from_pg_version }}/bin make ${{ inputs.test_make_target }}
        elif [ ${{ inputs.isolation }} == 'true' ]; then
          export PATH=$PGDIR/lib/pgxs/src/test/isolation:$PATH
          make ${{ inputs.test_make_target }}
        else
          make ${{ inputs.test_make_target }}
        fi
